name: Build Catalog API Image

on:
  push:
    paths:
      - catalog-api/**
      - .github/workflows/catalog-api*.yml
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Build with Thundra
        uses: thundra-io/thundra-gradle-test-action@v1
        with:
          apikey: 2a0ad462-59bb-4c4d-9d43-ab3705aad4c8
          project_id: 68b8e211-fbee-4cc5-9794-34912c05452c
          command: ./gradlew clean verifierStubsJar :catalog-api:build :catalog-api:bootJar -Dorg.gradle.daemon=false --rerun-tasks

      - name: Upload Jar File
        uses: actions/upload-artifact@v1
        with:
          name: catalog-api-jar
          path: catalog-api/build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          dockerfile: ./catalog-api/Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: catalog-api
          push: true
          tags: berk2s/b2b-catalogapi:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
